package com.pixelfitquest.feature.achievements.model

/**
 * Static local catalog. IDs `bronze_workout_1`, `silver_workout_10`, and
 * `gold_workout_50` match the original home-dialog trio so later migration
 * can reuse unlock state.
 */
object AchievementCatalog {
    val all: List<AchievementDefinition> = listOf(
        achievement(
            id = "bronze_workout_1",
            name = "Rookie",
            description = "Complete 1 workout",
            category = AchievementCategory.WORKOUTS,
            tier = AchievementTier.BRONZE,
            metric = AchievementMetric.WORKOUTS_COMPLETED,
            threshold = 1,
            coins = 10,
            xp = 25,
        ),
        achievement(
            id = "iron_workout_5",
            name = "Regular",
            description = "Complete 5 workouts",
            category = AchievementCategory.WORKOUTS,
            tier = AchievementTier.BRONZE,
            metric = AchievementMetric.WORKOUTS_COMPLETED,
            threshold = 5,
            coins = 15,
            xp = 40,
        ),
        achievement(
            id = "silver_workout_10",
            name = "Veteran",
            description = "Complete 10 workouts",
            category = AchievementCategory.WORKOUTS,
            tier = AchievementTier.SILVER,
            metric = AchievementMetric.WORKOUTS_COMPLETED,
            threshold = 10,
            coins = 25,
            xp = 75,
        ),
        achievement(
            id = "steel_workout_25",
            name = "Grinder",
            description = "Complete 25 workouts",
            category = AchievementCategory.WORKOUTS,
            tier = AchievementTier.SILVER,
            metric = AchievementMetric.WORKOUTS_COMPLETED,
            threshold = 25,
            coins = 40,
            xp = 120,
        ),
        achievement(
            id = "gold_workout_50",
            name = "Legend",
            description = "Complete 50 workouts",
            category = AchievementCategory.WORKOUTS,
            tier = AchievementTier.GOLD,
            metric = AchievementMetric.WORKOUTS_COMPLETED,
            threshold = 50,
            coins = 100,
            xp = 250,
        ),
        achievement(
            id = "platinum_workout_100",
            name = "Immortal",
            description = "Complete 100 workouts",
            category = AchievementCategory.WORKOUTS,
            tier = AchievementTier.PLATINUM,
            metric = AchievementMetric.WORKOUTS_COMPLETED,
            threshold = 100,
            coins = 200,
            xp = 500,
        ),
        achievement(
            id = "streak_3",
            name = "On Fire",
            description = "Reach a 3-day streak",
            category = AchievementCategory.STREAK,
            tier = AchievementTier.BRONZE,
            metric = AchievementMetric.CURRENT_STREAK,
            threshold = 3,
            coins = 10,
            xp = 30,
        ),
        achievement(
            id = "streak_7",
            name = "Week Warrior",
            description = "Reach a 7-day streak",
            category = AchievementCategory.STREAK,
            tier = AchievementTier.SILVER,
            metric = AchievementMetric.CURRENT_STREAK,
            threshold = 7,
            coins = 20,
            xp = 60,
        ),
        achievement(
            id = "streak_14",
            name = "Unstoppable",
            description = "Reach a 14-day streak",
            category = AchievementCategory.STREAK,
            tier = AchievementTier.GOLD,
            metric = AchievementMetric.CURRENT_STREAK,
            threshold = 14,
            coins = 40,
            xp = 120,
        ),
        achievement(
            id = "streak_30",
            name = "Habit Hero",
            description = "Reach a 30-day streak",
            category = AchievementCategory.STREAK,
            tier = AchievementTier.PLATINUM,
            metric = AchievementMetric.CURRENT_STREAK,
            threshold = 30,
            coins = 100,
            xp = 300,
        ),
        achievement(
            id = "steps_5000",
            name = "First Miles",
            description = "Walk 5,000 lifetime steps",
            category = AchievementCategory.STEPS,
            tier = AchievementTier.BRONZE,
            metric = AchievementMetric.LIFETIME_STEPS,
            threshold = 5_000,
            coins = 10,
            xp = 20,
        ),
        achievement(
            id = "steps_10000",
            name = "Walker",
            description = "Walk 10,000 lifetime steps",
            category = AchievementCategory.STEPS,
            tier = AchievementTier.BRONZE,
            metric = AchievementMetric.LIFETIME_STEPS,
            threshold = 10_000,
            coins = 15,
            xp = 40,
        ),
        achievement(
            id = "steps_50000",
            name = "Roadster",
            description = "Walk 50,000 lifetime steps",
            category = AchievementCategory.STEPS,
            tier = AchievementTier.SILVER,
            metric = AchievementMetric.LIFETIME_STEPS,
            threshold = 50_000,
            coins = 30,
            xp = 80,
        ),
        achievement(
            id = "steps_100000",
            name = "Marathoner",
            description = "Walk 100,000 lifetime steps",
            category = AchievementCategory.STEPS,
            tier = AchievementTier.GOLD,
            metric = AchievementMetric.LIFETIME_STEPS,
            threshold = 100_000,
            coins = 75,
            xp = 200,
        ),
        achievement(
            id = "volume_1000",
            name = "Iron Novice",
            description = "Lift 1,000 kg total volume",
            category = AchievementCategory.VOLUME,
            tier = AchievementTier.BRONZE,
            metric = AchievementMetric.TOTAL_VOLUME_KG,
            threshold = 1_000,
            coins = 15,
            xp = 40,
        ),
        achievement(
            id = "volume_10000",
            name = "Iron Veteran",
            description = "Lift 10,000 kg total volume",
            category = AchievementCategory.VOLUME,
            tier = AchievementTier.SILVER,
            metric = AchievementMetric.TOTAL_VOLUME_KG,
            threshold = 10_000,
            coins = 40,
            xp = 100,
        ),
        achievement(
            id = "volume_50000",
            name = "Iron Titan",
            description = "Lift 50,000 kg total volume",
            category = AchievementCategory.VOLUME,
            tier = AchievementTier.GOLD,
            metric = AchievementMetric.TOTAL_VOLUME_KG,
            threshold = 50_000,
            coins = 100,
            xp = 250,
        ),
        achievement(
            id = "sets_10",
            name = "Set Starter",
            description = "Complete 10 sets",
            category = AchievementCategory.VOLUME,
            tier = AchievementTier.BRONZE,
            metric = AchievementMetric.SETS_COMPLETED,
            threshold = 10,
            coins = 10,
            xp = 25,
        ),
        achievement(
            id = "sets_50",
            name = "Set Grinder",
            description = "Complete 50 sets",
            category = AchievementCategory.VOLUME,
            tier = AchievementTier.SILVER,
            metric = AchievementMetric.SETS_COMPLETED,
            threshold = 50,
            coins = 25,
            xp = 75,
        ),
        achievement(
            id = "sets_200",
            name = "Set Machine",
            description = "Complete 200 sets",
            category = AchievementCategory.VOLUME,
            tier = AchievementTier.GOLD,
            metric = AchievementMetric.SETS_COMPLETED,
            threshold = 200,
            coins = 80,
            xp = 200,
        ),
        achievement(
            id = "level_5",
            name = "Apprentice",
            description = "Reach level 5",
            category = AchievementCategory.MILESTONES,
            tier = AchievementTier.BRONZE,
            metric = AchievementMetric.LEVEL_REACHED,
            threshold = 5,
            coins = 20,
            xp = 50,
        ),
        achievement(
            id = "level_10",
            name = "Adventurer",
            description = "Reach level 10",
            category = AchievementCategory.MILESTONES,
            tier = AchievementTier.SILVER,
            metric = AchievementMetric.LEVEL_REACHED,
            threshold = 10,
            coins = 40,
            xp = 100,
        ),
        achievement(
            id = "level_20",
            name = "Champion",
            description = "Reach level 20",
            category = AchievementCategory.MILESTONES,
            tier = AchievementTier.GOLD,
            metric = AchievementMetric.LEVEL_REACHED,
            threshold = 20,
            coins = 80,
            xp = 200,
        ),
        achievement(
            id = "unique_3",
            name = "Variety Pack",
            description = "Train 3 different exercises",
            category = AchievementCategory.MILESTONES,
            tier = AchievementTier.BRONZE,
            metric = AchievementMetric.UNIQUE_EXERCISES,
            threshold = 3,
            coins = 15,
            xp = 40,
        ),
        achievement(
            id = "unique_8",
            name = "Full Roster",
            description = "Train 8 different exercises",
            category = AchievementCategory.MILESTONES,
            tier = AchievementTier.SILVER,
            metric = AchievementMetric.UNIQUE_EXERCISES,
            threshold = 8,
            coins = 35,
            xp = 90,
        ),
    )

    private val index: Map<String, AchievementDefinition> = all.associateBy { it.id }

    fun byId(id: String): AchievementDefinition? = index[id]

    val legacyWorkoutIds: Set<String> = setOf(
        "bronze_workout_1",
        "silver_workout_10",
        "gold_workout_50",
    )
}

private fun achievement(
    id: String,
    name: String,
    description: String,
    category: AchievementCategory,
    tier: AchievementTier,
    metric: AchievementMetric,
    threshold: Long,
    coins: Int,
    xp: Int,
): AchievementDefinition = AchievementDefinition(
    id = id,
    name = name,
    description = description,
    category = category,
    tier = tier,
    metric = metric,
    threshold = threshold,
    reward = AchievementReward(coins = coins, xp = xp),
)
